@startuml
left to right direction
skinparam packageStyle rectangle

actor Administrador
actor Visualizador
actor Contribuyente

rectangle "Sistema MetaMapa" {

    usecase "Crear colección" as UC1
    usecase "Importar hechos desde CSV" as UC2
    usecase "Ver hechos de una colección" as UC3
    usecase "Filtrar hechos de una colección" as UC4
    usecase "Solicitar eliminación de un hecho" as UC5
    usecase "Aceptar/rechazar solicitud de eliminación" as UC6

    Administrador --> UC1
    Administrador --> UC2
    Administrador --> UC6

    Visualizador --> UC3
    Visualizador --> UC4

/'    Visualizador --> UC5'/

    Contribuyente --> UC4
    Contribuyente --> UC5

/'El contribuyente puede solicitar la eliminacion de un hecho
si bien el visualizador puede llegar a ser un contribuyente, no lo es hasta que no contribuya'/
}

@enduml
