@startuml
left to right direction
skinparam classAttributeIconSize 0

'---------------------- Usuarios ----------------------
class Usuario {
    -nombre: String
    -apellido: String
    -edad: Integer
    -rol: Rol

    +verHecho(): A DEFINIR
}

interface Rol {
    +solicitarEliminacion(): SolicitudEliminacion
    +aportarHecho()
}

class Visualizador implements Rol {
    +solicitarEliminacion(): SolicitudEliminacion
    +aportarHecho()
}

class Contribuyente implements Rol {
    +solicitarEliminacion(): SolicitudEliminacion
    +aportarHecho()
}

class Administrador {

    +solicitarEliminacion(): SolicitudEliminacion
    +gestionarSolicitudes()
    +crearColeccion(): Coleccion
    +importarCSV()
}

Usuario --> Rol
Administrador --> SolicitudEliminacion
Visualizador --> SolicitudEliminacion
Contribuyente --> SolicitudEliminacion

'---------------------- Solicitud Eliminación ----------------------
class SolicitudEliminacion {
    -hecho: Hecho
    -motivo: String
    -estado: EstadoSolicitud

    +aceptar()
    +rechazar()
}

enum EstadoSolicitud {
    PENDIENTE
    ACEPTADA
    RECHAZADA
}

SolicitudEliminacion --> Hecho
SolicitudEliminacion --> EstadoSolicitud

'---------------------- Colecciones ----------------------
class Coleccion {
    -hechos: List<Hecho>
    -fuente: FuenteDatos
    -titulo: String
    -descripcion: String
    -crierioDePertenencia: List<CriterioDePertenencia>

    +leerColeccion(): List<Hecho>
}

interface CriterioDePertenencia {
    +cumple(hecho: Hecho): boolean
}

class CriterioPorUbicacion implements CriterioDePertenencia {
    -ubicacion: Ubicacion
    +cumple(hecho: Hecho): boolean
}

class CriterioPorFecha implements CriterioDePertenencia {
    -desde: LocalDate
    -hasta: LocalDate
    +cumple(hecho: Hecho): boolean
}

class CriterioPorCategoria implements CriterioDePertenencia {
    -categoria: Categoria
    +cumple(hecho: Hecho): boolean
}

Coleccion --> "*" Hecho
Coleccion --> FuenteDatos
Coleccion --> "*" CriterioDePertenencia
CriterioPorCategoria --> Categoria
CriterioPorUbicacion --> Ubicacion

'---------------------- Hechos ----------------------
class Hecho {
    -titulo: String
    -descripcion: String
    -categoria: Categoria
    -ubicacion: Ubicacion
    -fechaDeCarga: Date
    -fecha: Date
    -contenidoMultimedia: Contenido
    -origen: Origen
    -tags: List<String>
}

class Categoria {
    -nombre: String
}

enum Origen {
    CARGA_MANUAL
    DATASET
    CONTRIBUYENTE
}

class Ubicacion {
    -latitud: Double
    -longitud: Double
}

enum Contenido {
    -FOTO
    -VIDEO
}

Hecho --> Categoria
Hecho --> Ubicacion
Hecho --> Origen
Hecho --> Contenido

'---------------------- Filtros de Hechos ----------------------
interface FiltroHechos {
    +cumple(hecho: Hecho): boolean
}

class FiltroTexto implements FiltroHechos {
    -texto: String
    +cumple(hecho: Hecho): boolean
}

FiltroHechos ..> Hecho

'---------------------- Fuentes de Datos ----------------------
interface FuenteDatos {
    +obtenerHechos(): List<Hecho>
}

class FuenteEstatica implements FuenteDatos {
    -dataset: String
    -lector: Lector
    +obtenerHechos(): List<Hecho>
}

class FuenteDinamica implements FuenteDatos {
    +obtenerHechos(): List<Hecho>
}

FuenteEstatica --> Lector

'---------------------- Lectores ----------------------
interface Lector {
    +obtenerDatos(String)
}

class LectorCSV implements Lector {

    +obtenerDatos(String)
}

@enduml