@startuml

'----------------------Usuarios:-------------------'

class Usuario {
    -nombre: String
    -apellido: String
    -edad: Integer
    -rol: Rol

    +verHecho(): A DEFINIR
}

interface Rol{
     +solicitarEliminacion(): SolicitudEliminacion
     +aportarHecho()
}

class Visualizador implements Rol {
     +solicitarEliminacion(): SolicitudEliminacion
     +aportarHecho()
}

class Contribuyente implements Rol {
     +solicitarEliminacion(): SolicitudEliminacion
     +aportarHecho()
}

class Administrador{

    +solicitarEliminacion(): SolicitudEliminacion
    +gestionarSolicitudes()
    +crearColeccion(): Coleccion
    +importarCSV()
}

Usuario -> Rol
Administrador -> Fundamento
Administrador -> SolicitudEliminacion
Visualizador -> SolicitudEliminacion
Contribuyente -> SolicitudEliminacion

'-------------------------Solicitud-Eliminacion-----------------------'
class SolicitudEliminacion {
    -hecho: Hecho
    -motivo: String
    -estado: EstadoSolicitud

    +aceptar()
    +rechazar()
}

interface Fundamento{
    +cumple():Boolean
}
class fundamento500c implements Fundamento{
    +cumple():Boolean
}

SolicitudEliminacion -> Hecho
SolicitudEliminacion -> EstadoSolicitud
'-------------------------Colecciones-------------------------'
Class Coleccion {
    -hechos:List<Hecho>
    -fuente: FuenteDatos
    -titulo: String
    -descripcion: String
    -crierioDePertenencia: List<CriterioDePertenencia>

    +leerColeccion():List<Hecho>
}

Coleccion -> Hecho
Coleccion -> FuenteDatos
Coleccion -> CriterioDePertenencia

'-------------------------Criterios-Pertenencia-------------------------'
interface CriterioDePertenencia {
  +cumple(hecho: Hecho): boolean
}


class CriterioPorUbicacion implements CriterioDePertenencia {
  -ubicacion: Ubicacion

  +cumple(hecho: Hecho): boolean
}

class CriterioPorRangoDeFecha implements CriterioDePertenencia {
  -desde: LocalDate
  -hasta: LocalDate

  +cumple(hecho: Hecho): boolean
}

class CriterioPorCategoria implements CriterioDePertenencia {
  -categoria: Categoria

  +cumple(hecho: Hecho): boolean
}

CriterioPorCategoria -> Categoria
CriterioPorUbicacion -> Ubicacion


'-------------------------Hechos---------------------------'
Class Hecho {
    -titulo: String
    -descripcion: String
    -categoria: Categoria
    -ubicacion: Ubicacion
    -fechaDeCarga: Date
    -fecha: Date
    -contenidoMultimedia: Contenido
    -origen: Origen
    -tags: List<Tags>
}

Hecho -> Categoria
Hecho -> Ubicacion
Hecho -> Origen
Hecho -> Contenido

'-------------------------Filtros-Hechos-------------------------------'
interface FiltroHechos {
  +cumple(hecho: Hecho): boolean
}


class FiltroTexto implements FiltroHechos {
  -texto: String
  +cumple(hecho: Hecho): boolean
}

class FiltroMultimedia implements FiltroHechos {
  -contenido: Contenido
  +cumple(hecho: Hecho): boolean
}

FiltroMultimedia -> Contenido

'-------------------------FUENTES-------------------------------'
interface FuenteDatos {
    +obtenerHechos(): List<Hecho>
}

Class FuenteDatosEstatica implements FuenteDatos{

    -dataset: String
    -lector: Lector

    +obtenerHechos(): List<Hecho>
    +extraerDatos(SQL): List<Hecho>
    +extraerDatos(csv): List<Hecho>
    +extraerDatos(word): List<Hecho>
}

Class FuenteDatosDinamica implements FuenteDatos {
    +obtenerHechos(): List<Hecho>
}

FuenteDatosEstatica --> Lector

'-------------------------INTERFAZ GRÁFICA----------------------'
Class InterfazGrafica {
    +leer (List<Hecho>)
    +leer (List<Hecho>, List<FiltroHechos>)
    +leer (Coleccion)
    +leer (Coleccion, List<FiltroHechos>)
}

'----------LECTOR CSV ---------------

interface Lector {

    +obtenerDatos(String)
 }

 Class LectorCSV implements Lector {

    +obtenerDatos(String)
 }


'-------------------------ENUMS Y AUX---------------------------'
enum Categoria {
    INCENDIO
    DESAPARICION
    CONTAMINACION
    OTRO
}

enum EstadoSolicitud {
    PENDIENTE
    ACEPTADA
    RECHAZADA
}

enum Origen {
    CARGA_MANUAL
    DATASET
    CONTRIBUYENTE
}

Class Ubicacion {
    -latitud: Double
    -longitud: Double
}

enum Contenido {
    -FOTO
    -VIDEO
}

enum Tags {
}

@enduml